### ISSUE TITLE
Project folder

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#1]
Hi @manowb ,
I try to write some details on the project modifications.

1. As I said you, we added a [gitignore](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/.gitignore). Maybe it is too strict: keeping the original `.classpath` and `.project` files solves the installation issues that I was talking about last friday. So in next commit, we are going to restore these files. However, we agree that it is better that the `bin` folder continues to be excluded from commits.

2. In the ['suggestion' branch](https://github.com/DOREMUS-ANR/marc2rdf/tree/suggestion), we propose a different structure for directories. In this version, all Java sources are in the `src` folder, that is organized in 5 package (the 4 modules you have identified, plus the `main` package). Each package follows the naming convention `org.doremus.marc2rdf.packageName`. The main reason is aligning the project to [what conventionally developers do](http://blog.recurtrix.com/2012/07/how-to-organize-eclipse-project.html). What do you think about it?

3. Currently in the project there are two folders, `Data` and `data`. Following conventions, we should use the lowercase version, or rename it `resources`.

Then, Eva still has some doubt about the new version of the code. It is ok for you using GitHub issues for questions about coding? So that, it will easier reference files or line of code.

Thank you very much

**Comment by manowb** [comment]
Hi @pasqLisena,

Thank you for the explanation about the project modifications. It is OK for gitignore. and for your suggestion about restructuring the directories. 

I don't know why there are two folders "Data" and "data". In my eclipse project there is only one. 

Is it OK for you if I make now another commit to resolve it and integrate suggestions?

Of course, we can use GitHub issues to communicate :)

**Comment by pasqLisena** [comment]
> I don't know why there are two folders "Data" and "data". In my eclipse project there is only one.

Yes, in mine too. I think that when pulling in local, git solves the path, automatically.

> Is it OK for you if I make now another commit to resolve it and integrate suggestions?

Yes, of course. We will wait for that. :smile:

> Of course, we can use GitHub issues to communicate :)

Very good. Soon @fernanev will contact you.

Thank you very much. I'm available for any problem or doubt

**Comment by pasqLisena** [comment]
With my last commits, I have:
- removed the `Data`, moving all their files in `data`. Please everyone, check if also locally you have the correct name; if not, manually correct it.
- solved 1.

I am going to close the suggestion branch. The master branch could be now the starting point for any future editing. :+1: 

Thank you
