### ISSUE TITLE
Improvements on genres vocabulary matching

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#10]
How it is working now:

1. Search for a genre code in the MARC file  ( F22_SelfContainedExpression.java ), e.g. ```mld```
2. Find the match in [GenresBNF.xlsx](../blob/master/src/main/resources/GenresBNF.xlsx), e.g. ```melodie@fr```
3. Add temporary the property ```U12_has_genre``` with the literal as value
4. After the RDF creation, the "string2uri" part searches for the literal string in the [vocabulary](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/genre.ttl)
5. The literal is replaced with the URI defined in SKOS, e.g. <http://data.doremus.org/vocabulary/genre/mld>

### Limits
1. We are doing a double jump (from code to label, then again to code)
2. Some label are shared between different genres ... e.g. ```operetta@it``` can fall both in ```ops``` and ```opt```
3. Values that are not in the excel file can be discarded, but the code could be in the vocabulary. It happens very often with ```zz#``` = ```other form@en```
4. Do it afterwards could have unexpected situation: what happens if the title of a work is exactly ```Concerto```? (@rtroncy I wish to know also your opinion on this :) )

Note that the vocabulary contains the whole GenresBNF.xlsx, GenresIAML.xlsx and the other [AIBM genres](http://www.urfm.braidense.it/risorse/forme_query_en.php).

### My proposal
Use the vocabulary directly at step 2. (instead of GenresBNF.xlsx) and replace directly with the final URI.

-------------------
**Related question** for @marie-ototoi The [`uuu` or "unknow"](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/genre.ttl#L3600) is conceptually the same of `###` or ```non renseigné```?
* [ ] If yes, we can merge these values.
* [ ] If not, we should find another code for the latter (better avoid the `#`).

**Comment by rtroncy** [comment]
Thanks @pasqLisena for this great summary. I have slightly edited your issue for better readibility in github. I have tagged @marie-ototoi for the last question (we need a IAML expert :-).

Regarding the bulk of the issue, +1 for the proposal ... we should NOT go via [GenresBNF.xlsx](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/src/main/resources/GenresBNF.xlsx) and we should directly assign the proper URI in step 2. @pasqLisena are you volunteering to fix this in the code? Last remark: are we sure this is a deterministic process, i.e that the ```genre``` found in the MARC file will always refer to exactly 1 code in our SKOS? Should we have an error case where we don't find the code? Is the code really unique (no substring)?

**Comment by pierrechoffe** [comment]
@pasqLisena @marie-ototoi
thanks for this !
uu and zz have different labels, but very often they are used for the same "idea" i.e. "i don't know how to categorize this work". Therefore I suggest they could be merged, and they also are (more or less) equivalent to "non renseigné". They are used a lot for contemporary music because genres can be somewhat fuzzy.
regarding operetta : this one is opt and definitely not ops (which is opera seria), so they should not be merged.

**Comment by rtroncy** [comment]
@pierrechoffe: nobody has suggested to merge ```operetta```. @pasqLisena was just mentioning that this is a label that you can find for two different codes: ```opt``` and ```ops```. Are you saying that one of this label is wrong?

@pierrechoffe: am I understanding well that you propose to have 1 unique code (and what will be the code and the labels?) that merges: ```uu```, ```zz``` and ```non rensesigné```?

**Comment by pasqLisena** [comment]
Answering questions:

> are you volunteering to fix this in the code?

Yes, I can do it.

> are we sure this is a deterministic process, i.e that the genre found in the MARC file will always refer to exactly 1 code in our SKOS? Should we have an error case where we don't find the code?

The generation of our SKOS has been made by @fernanev. She merged three sources ( [GenresBNF.xlsx](../blob/master/src/main/resources/GenresBNF.xlsx), [GenresIAML.xlsx](../blob/master/src/main/resources/genresIAML.xlsx) and the [AIBM genres table](http://www.urfm.braidense.it/risorse/forme_query_en.php) ).
It does not contain MORE then 1 code for each MARC genre.
If the sources excel files are complete (and it seems to be so by the test on the `Thematic Corpus` data), then it also does not contain LESS then 1 code for each MARC genre and we should find the code.

> Is the code really unique (no substring)?

I am not sure about what you mean. Can you write an example?

>  @pasqLisena was just mentioning that this is a label that you can find for two different codes: opt and ops.

I confirm, you can find _operetta_ both for [opt](http://www.urfm.braidense.it/risorse/forme_query_en.php?Ricarica=opt) and [ops](http://www.urfm.braidense.it/risorse/forme_query_en.php?Ricarica=ops).

**Comment by rtroncy** [comment]
>> Is the code really unique (no substring)?

> I am not sure about what you mean. Can you write an example?

An hypothetic example would be to have ```mld``` as a valid code and ```mldb``` or ```amld``` as another code where a code string could be substring of another code string. Can this happen? Or is the code always represented with 3 characters?

**Comment by pasqLisena** [comment]
> is the code always represented with 3 characters?

The code are represented with 3 characters (`syc`	 = `symphonie concertante`) or with 2 characters and a `#` (`sy#` = `symphony`). The latter seems to be a superset of the former, but I am not sure that it is for every case (if it is so, we can add the SKOS `narrower`\`broader` properties).

Sometimes, the MARC contains only the first 2 character (`sy`) and the `#` is added by our application, according with the mapping documents.

So yes, from the MARC we can identify an unique code.

**Comment by rtroncy** [comment]
@marie-ototoi @pierrechoffe Given that you're our designated experts in parsing IAML codes, can you confirm that we will systematically have a hierarchical relationship when a 3 characters codes extend a 2 characters code (like in the ```sy``` and ```syc``` example) that we should materialize with a ```skos:broader``` / ```skos:narrower``` relationship?

**Comment by pasqLisena** [comment]
I just committed a fix.

**What happens now** (waiting for different instructions in case):

1. BNF Converter (MARC file contains codes)
 - Referencing is made **matching codes** (the one in the MARC and the one in the vocabulary). According to test on _Thematic Corpus_, every code match one Concept in vocabulary.
 - `uu` and `zz` are matched to the corresponding properties in the vocabulary (so, `unknow` and `other form`)
 - `###` is actually written in the MARC as `   ` (3 blank spaces).
    - Previously was mapped to `non renseigné`.
    - Now, `U12_has_genre` property is simply **not added**.

2. Philarmonie Converter (MARC file contains labels)
 - The referencing is done **after** MARC parsing
 - **Known labels** are correctly referenced
    - `mus:U12_has_genre <http://data.doremus.org/vocabulary/genre/co>`
 - **Unknow labels** are keeped as label
   - `mus:U12_has_genre [ cidoc-crm:P1_is_identified_by  "musique contemporaine"@fr ]`
 - If not genre is found, the property is not added

New feature:
 - If a record has **multiple genres**, all of them are parsed and added to the final rdf

**Comment by rtroncy** [comment]
Excellent! So can this issue be closed?

**Comment by pasqLisena** [comment]
I think there are still unanswered question (at least [this](#issuecomment-222936109)).

**Comment by rtroncy** [comment]
Correct, waiting for the answer from @marie-ototoi or @pierrechoffe then

**Comment by pierrechoffe** [comment]
Hi everyone,
Q1 @rtroncy : can you confirm that we will systematically have a hierarchical relationship when a 3 characters codes extend a 2 characters code (like in the sy and syc example) that we should materialize with a skos:broader / skos:narrower relationship?
A1 : no, at least in the BnF genres there is no _systematical_ hierarchical relationship. You might have e.g. sy (symphony), syc (symphonie concertante)and syd (symphonie dramatique), but then sym (symbolum). 
You also have sn (sonata) and snd (serenade) which have nothing in common, and lots of such examples.
We could add a `skos:broader / skos:narrower` relationship but this wold have to be manually.

Q2 @pasqLisena : Some label are shared between different genres ... e.g. operetta@it can fall both in ops and opt
A2 : I checked the genre.ttl file and yes you are right operetta@it is shared between opt and ops. Operetta is definitely opt. I don't know how ops could include operetta, this has to be investigated with the other experts. ops is Opera Seria, which is exactly the contrary of Operetta. So, we will check whether one of the institutions uses the ops in a different way and how we can solve this.

Q3 @rtroncy : am I understanding well that you propose to have 1 unique code (and what will be the code and the labels?) that merges: uu, zz and non renseigné?
A3 : yes definitely. In theory, they are not exactly the same, but cataloguers use them without distinction when they don't know how to describe the genre, so they end up having the same meaning. The best label would be "non renseigné".

**Comment by rtroncy** [comment]
I have re-edited your comment @pierrechoffe to be markdown friendly.
In Q1, there are two sub-questions: a) is there some hierarchy between the genres? b) assuming there is one, how can we infer it? You're saying that we cannot infer it based on the usage of a 2 letters code vs 3 letters code. What other means do we have?
In Q3, "non renseigné" might be the best label ```@fr``` not in ```@en```. We should also look beyond the usage of BnF

**Comment by pierrechoffe** [comment]
@rtroncy Q3 : sure we should also have an @en label. And sure enough, we should take into consideration the usage of all 3 institutions.
Q1 : a) yes, there is a hierarchy between genres but b) you cannot infer it from the usage of the 2 letters code. There are many exceptions of different kinds. I would suggest that this be done manually. My list of BnF genres has 259 names (300 if we take less frequent names, 600 if we include theater etc), this should not be a herculean task. I don't know about the other institutions.
Furthermore, this manual overhaul would be justified by the existence of other types of relationships, like equivalent terms : mdy (melody) should be equivalent to mld (mélodie). So maybe we could also add more skos relationships.

**Comment by rtroncy** [comment]
OK, let's first gather the genre controlled vocabularies from all institutions in order to have a first reconciled version and let's add more structural relationships afterwards

**Comment by pasqLisena** [comment]
> > Q2 @pasqLisena : Some label are shared between different genres ... e.g. operetta@it can fall both in ops and opt

> A2 : I checked the genre.ttl file and yes you are right operetta@it is shared between opt and ops. Operetta is definitely opt. I don't know how ops could include operetta, this has to be investigated with the other experts. ops is Opera Seria, which is exactly the contrary of Operetta. So, we will check whether one of the institutions uses the ops in a different way and how we can solve this.

@pierrechoffe It make sense. Just to help you in your checking process: we took the codes/labels from [this database](http://www.urfm.braidense.it/risorse/forme_query_en.php), that we found linked on the [IAML site](http://www.iaml.info/unimarc-field-128-musical-forms).

**Comment by pierrechoffe** [comment]
@pasqLisena @rtroncy So, I checked on the URFM site and I found this operetta in ops. Actually, this is a "local" adaptation of AIBM (making the arguable assumption that the operetta genre changed between 18th and 19th century).
Since we are aligned on AIBM and not URFM, Frédéric Puyrenier thinks that we could as well consider that operetta is opt and NOT ops.
You may also have an "operetta drammatica" in ops : this one can stay in ops :)

**Comment by pasqLisena** [comment]
Solved in the other repo. I close this issue.

**Comment by rtroncy** [comment]
Indeed, discussions are ongoing in the [Knowledge Base repository](https://github.com/DOREMUS-ANR/knowledge-base/).
@pierrechoffe, our starting point was the IAML genre list, and not the URFM one, so I'm puzzled.

**Comment by pierrechoffe** [comment]
As I understand it URFM database was used to access musical forms (see Pasquale message : @pierrechoffe <https://github.com/pierrechoffe> It make sense. Just to help you in your checking process: we took the codes/labels fromthis database <http://www.urfm.braidense.it/risorse/forme_query_en.php>, that we found linked on the IAML site <http://www.iaml.info/unimarc-field-128-musical-forms>.) . 
Indeed, on IAML site there is a link to URFM :
At http://www.urfm.braidense.it/risorse/searchforms_en.php(link is external) <http://www.urfm.braidense.it/risorse/searchforms_en.php> you can find a searchable database for musical forms, hosted by Ufficio Ricerca Fondi Musicali - Biblioteca Nazionale Braidense.
But apparently, this database has further added musical forms and/or changed some categorizations (distinction between 18th century and 19th century operetta). I will check again with Frédéric.
