### ISSUE TITLE
Should all nodes in the RDF graph be typed?

### ISSUE THREAD

**Issue by fernanev** [DOREMUS-ANR/marc2rdf#13]
- [x] **1. BNF and PP Converters**
Should all blank nodes have RDF type? Some of them still doesn't have, for example:
```.turtle
mus:U17_has_opus_statement   [ cidoc-crm:P106_is_composed_of  "73" ;
                               cidoc-crm:P3_has_note          "Op. 73"
                             ] ;
```

- [x] **2. BNF Converter**

F22_Self_Contained_Expression has two RDF types for example:
``` .turtle
<http://data.doremus.org/Self_Contained_Expression/F22/7cf25xxx>
        a   frbroo:F22_Self-Contained_Expression , mus:Self_Contained_Expression ;
```
Should `mus:...` be removed?

- [x] **3. PP Converter**
When specifying the RDF type of Denomination Controlled Acces Point, we could do it more readable converting this:
``` .turtle
<http://data.doremus.org/Denomination_Controlled_Access_Point/M18/08960xxx>
        a    <http://data.doremus.org/ontology#M18_Controlled_Access_Point_Denomination> ;
```
in this:
``` .turtle
<http://data.doremus.org/Denomination_Controlled_Access_Point/M18/08960xx>
        a    mus:M18_Controlled_Access_Point_Denomination ;
```

**Comment by rtroncy** [comment]
Part 1: blank nodes should be avoided in the first place, and they MUST be typed, so indeed, a type should be added.

Part 2: this was clearly a mistake, thanks for the fix @pasqLisena 

Part 3: I agree @fernanev

**Comment by pasqLisena** [comment]
Question related to Part 3.

Our namespace is
 - `http://data.doremus.org/ontology#`, like in the [Protege project](https://github.com/DOREMUS-ANR/doremus-ontology/blob/master/Doremus-v0.1.owl#L12)

or

-  `http://data.doremus.org/ontology/`, like exported currently by marc2rdf?

I introduced the problem 3 because I relied on the protege version, and I have not realized of the presence of the latter in the code.

**Comment by pierrechoffe** [comment]
@fernanev @pasqLisena FYI I created some new properties in order to make relationships clearer when we (erroneously) relied on class names, e.g we had:
```
mus:U17_has_opus_statement   [ cidoc-crm:P106_is_composed_of  "27" ;  
                               cidoc-crm:P106_is_composed_of  "2" ;  
                               cidoc-crm:P3_has_note  "Op. 27 no 2"
                             ] ;
```
now we would have:
```
mus:U17_has_opus_statement   [ mus:U42_has_opus_number  "27" ;  
                               mus:U43_has_opus_subnumber  "2" ;  
                               cidoc-crm:P3_has_note  "Op. 27 no 2"
                             ] ;
```
Same thing for catalogue statement.
Should I update Protégé ?

**Comment by pasqLisena** [comment]
> Should I update Protégé ?

Yes, please. Thank you.

**Comment by rtroncy** [comment]
We should privilege the # version for the ontology (not the / version). Can you either fix MARC2RDF or record a new issue?

**Comment by pasqLisena** [comment]
For Part 1, the type should be added in multiple parts of the code.

My next commit will fix it for keys and genres, but probably will be not enough. Please @fernanev can you list every blank node without type?

**Comment by pierrechoffe** [comment]
@pasqLisena @fernanev just updated the DOREMUS ontology on Protégé

**Comment by rtroncy** [comment]
@pierrechoffe Reminder, use the [doremus-ontology](https://github.com/DOREMUS-ANR/doremus-ontology) repository for issues related to the ontology.

**Comment by fernanev** [comment]
> Please @fernanev can you list every blank node you find without type?

Yes, no problem, I will do that list asap.
