### ISSUE TITLE
Optional group of classes

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#19]
Here are the classes that we currently instantiate in marc2rdf:

- [x] **1. Group Work/Expression**
 - F22_SelfContainedExpression
 - F28_ExpressionCreation
 - F14_IndividualWork 
 - F15_ComplexWork
 - F42_RepresentativeExpressionAssignment

- [x] **2. Group Publication**
 - F24_PublicationExpression
 - F30_PublicationEvent
 - F19_PublicationWork

- [x] **3. Group Performance**
 - F31_Performance
 - F25_PerformancePlan
 - F25_AutrePerformancePlan
 - F31_AutrePerformance

- [x] **4. Group Identification**
 - F40_IdentifierAssignment
 - F50_ControlledAccessPoint _only for Philharmonie_

About the 3rd group, a refactoring is in progress in #5 .

------------

### Currently

For each record, the application makes one instances for each class (F22, F14, F15, F40, etc.). Here is the [relevant part of the code](../blob/master/src/main/java/org/doremus/marc2rdf/bnfconverter/RecordConverter.java#L15). 

### My proposal

For the **Group 1** this is ok: the record actually describe them. 

For **Groups 2 and 3**, the source xml does not contains the information all the time. It _could_ give us the info about the 1st execution, the 1st execution in France and the 1st publication, but not all the times. My proposal is to make them "optional" and include them in the output only if we have the info.

For **Group 4**, for sure we will add an instance, but for _notices d'oeuvre_  we could have multiple instances - see [#17](https://github.com/DOREMUS-ANR/marc2rdf/issues/17#issuecomment-237558387).

**Comment by rtroncy** [comment]
You made a typo in listing the possibilities in Group 3: you have twice F25 and F31 with different suffix names.

I agree that you should instantiate the classes and properties only when you have the information in the source data, and not systematically.

**Comment by pasqLisena** [comment]
> You made a typo in listing the possibilities in Group 3: you have twice F25 and F31 with different suffix names.

The typo was in the following note about the refactoring. I edited it now.

**Comment by rtroncy** [comment]
I don't understand. How can we have:  F31_Performance AND F31_AutrePerformance; F25_PerformancePlan AND F25_AutrePerformancePlan? Same Fxx but different concept?

**Comment by pasqLisena** [comment]
It should be refactored, there is an issue still open #5 but not yet resolved.

**Comment by pasqLisena** [comment]
Closed with [last commit](https://github.com/DOREMUS-ANR/marc2rdf/commit/05592603c5117481c8849de1139d7f130e9a4f55).
