### ISSUE TITLE
Bad language tag

### ISSUE THREAD

**Issue by manowb** [DOREMUS-ANR/marc2rdf#24]
Hello,

When the language is not known (in some cases and mostly for BNF records, it is specified by "**...**") , the converter generates the following error:

`Exception in thread "main" org.apache.jena.riot.RiotException: [line: 40, col: 44] Bad language tag`

The language tag must be well formed (@fr, @en, etc.). 

An example of such file is "**13908469.xml**" from BNF:

```
<http://data.doremus.org/expression/f35ca6a2-9a1f-3a47-a957-e3abfd8da9be>
        a                    efrbroo:F22_Self-Contained_Expression ;
        mus:U12_has_genre    <http://data.doremus.org/vocabulary/genre/zz> ;
        ecrm:P102_has_title  "Sequenza IX"@.. ;
        ecrm:P3_has_note     "Créé par Michel Arrignon" .
```
So, the points should not be considered !

**Comment by rtroncy** [comment]
In this particular case, the value of the ```ecrm:P102_has_title``` should not be language tagged
