### ISSUE TITLE
Duplicate URIs when converting BNF records

### ISSUE THREAD

**Issue by manowb** [DOREMUS-ANR/marc2rdf#25]
When converting several records at the same time, the converter generates for each class the same URI for all records.

Note that this appears only on BNF records. The PP records seem well converted (The URIs of all classes for all records are different).

Examples of such files : 

- [ ] 13908490.ttl 

```
<http://data.doremus.org/expression/f35ca6a2-9a1f-3a47-a957-e3abfd8da9be>
        a                    efrbroo:F22_Self-Contained_Expression ;
        mus:U12_has_genre    <http://data.doremus.org/vocabulary/genre/ov> ;
        mus:U16_has_catalogue_statement
                [ a                             mus:M1_Catalogue_Statement ;
                  mus:U40_has_catalogue_name    "H" ;
                  mus:U41_has_catalogue_number  "101B" ;
                  ecrm:P3_has_note              "H 101B"
                ] ;
        ecrm:P102_has_title  "Le corsaire"@fr , "Ouverture du corsaire"@fr ;
        ecrm:P3_has_note     "D'après James Fenimore Cooper (\"The Red Rover\")" , "Existe dans une première version, intitulée successivement \"La Tour de Nice\" et \"Le Corsaire rouge\", composée d'août à novembre 1844 (H 101A)" ;
        ecrm:P67_refers_to   <http://data.doremus.org/expression/f35ca6a2-9a1f-3a47-a957-e3abfd8da9be/dedication> .
```

- [ ] 13911580.ttl

```
<http://data.doremus.org/expression/f35ca6a2-9a1f-3a47-a957-e3abfd8da9be>
        a                    efrbroo:F22_Self-Contained_Expression ;
        mus:U12_has_genre    <http://data.doremus.org/vocabulary/genre/opu> ;
        ecrm:P102_has_title  "Don Pasquale"@it ;
        ecrm:P3_has_note     "Dramma buffo en 3 actes" , "Livret du compositeur et de Giovanni Ruffini d'après le livret d'Angelo Anelli pour l'opéra de Stefano Pavesi \"Ser Marcantonio\" (1810)" .
```

**Comment by rtroncy** [comment]
Ouch, well-spotted @manowb!

@pasqLisena, we do have normally a well-deterministic procedure for properly hashing the id of each resource in the graph. How come that those 2 different expressions get the same UUID? Can you review this part of the code (thinking that the converter might process batch of input files in a multi thread process)

**Comment by manowb** [comment]
@rtroncy  After having searched on the code what can cause the duplication of UUIDs, I found that in the case of the BNF records, the converter always gave the same UUID for all resources of the same class (For example for **F22**, the UUID is always : **_f35ca6a2-9a1f-3a47-a957-e3abfd8da9be_**)

[This instruction](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/src/main/java/org/doremus/marc2rdf/main/DoremusResource.java#L34) generates an UUID from the identifier of the record. However, this identifier is always equal to **_null_** for BNF records because the [identifier label](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/src/main/java/org/doremus/marc2rdf/marcparser/MarcXmlHandler.java#L238) for them is not "**_id_**" (like for the PP records) but it corresponds to "**_Numero_**".
