### ISSUE TITLE
[BnF] Implement mapping rules for bibliographic records

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#26]
In the [Mapping table of BnF](https://drive.google.com/file/d/0B4s5dBwAmhJsUXJrVnVtb19JMTA/view?usp=sharing) the rules for mapping bibliographic files (BIB) are also defined. They should be implemented.

**Comment by FLERESCHE** [comment]
Les notices TUM (Titre Uniforme Musical) sont des notices qui décrivent des oeuvres.
Les notices BIB (pour "bibliographiques") décrivent quant à elles des documents. Lorsque la modélisation des Manifestations sera validée, nous établirons des règles de mapping pour les notices bibliographiques.

Dans le cadre des spécifications de mapping pour les oeuvres, il y a des règles de mapping à partir de notices bibliographiques dans le cas d'arrangements ou de dérivations d'une oeuvre qui correspondent juste à une nouvelle expression de l'Oeuvre décrite dans une notice TUM (par exemple, une transcription pour un autre instrument, une réduction pour piano, etc). Dans ce cas, dans la notice bibliographique, il y a un lien vers la notice TUM de l'Oeuvre originale (en 144 ou 744 selon les cas) complété par une sous-zone $l pour indiquer de manière générique "arr." ou plus précise la nature de l'arrangement.
Dans ce cas, il faut créer une nouvelle F22/F14 pour la dérivation. Si la distribution instrumentale change par rapport à l'Oeuvre originale, la nouvelle distribution est indiquée dans la notice BIB dans la zone 048.

**Comment by pasqLisena** [comment]
duplicate of #32
