### ISSUE TITLE
Implement mapping rules for F40

### ISSUE THREAD

**Issue by manoach** [DOREMUS-ANR/marc2rdf#28]
Actually, the generated RDF does not describe the work identification especially in terms of rules used by the bibliographic agencies for cataloging (`F40 Identifier Assignment R52 used rule F43 Identifier Rule`):

- **BNF**:  `"NF Z 44-079 (Novembre 1993) - Documentation - Catalogage- Forme et structure des vedettes titres musicaux`"
- **PP**:  In case of:
1. UNI100:200$a  --> "`Usages de la Philharmonie de Paris`"
2. AIC14:144$a or AIC14:444$a --> "`NF Z 44-079 (Novembre 1993) - Documentation - Catalogage- Forme et structure des vedettes titres musicaux`"

An older version of the prototype described it. Why is it no longer taken into account?

**Comment by rtroncy** [comment]
I'm not sure I understand what is precisely your question @manoach. I have always argued that we should revisit the way controlled access points are modeled. In particular, we could in a first version model the result (i.e. the controlled access point) without describing the rules that constitute it. I need to see more examples from all providers. Meanwhile, what does the converter do at the moment? What is the current output in turtle?

**Comment by pasqLisena** [comment]
Close for being pending too much
