### ISSUE TITLE
DOREMUS uri for PP

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#29]
According to mapping rules, we set the Representative Expression in this way:

```ttl
<http://data.doremus.org/event/f887237f-239e-3844-b1be-f328763a00e2>
        a                           efrbroo:F42_Representative_Expression_Assignment ;
        efrbroo:R44_carried_out_by  <http://data.doremus.org/Philharmonie_de_Paris> ;
        efrbroo:R50_assigned_to     <http://data.doremus.org/work/96ba6f94-56ec-3805-8d03-372e249ecdd4> ;
        efrbroo:R51_assigned        <http://data.doremus.org/expression/82115b51-ae24-37c4-8091-7f1134f20e03> .

```

where `efrbroo:R44_carried_out_by` is the assignment actor. For the BnF we use `http://www.isni.org/isni/0000000121751303`.

What we should do with this? Some options:
1. `http://data.doremus.org/Philharmonie_de_Paris` (keep it as is, i will dereference it)
2. `http://data.doremus.org/artist/Philharmonie_de_Paris`
3. `http://data.doremus.org/institution/Philharmonie_de_Paris`
4. `http://www.isni.org/isni/0000000121834950` (isni of [Cité de la musique (Paris)](http://catalogue.bnf.fr/ark:/12148/cb12432023w)
5. `http://catalogue.bnf.fr/ark:/12148/cb16651244g`

**Comment by pierrechoffe** [comment]
another option could be viaf ?
http://viaf.org/viaf/315254866/#Philharmonie_de_Paris

**Comment by manoach** [comment]
I propose to use the ISNI identifier so that it is homogeneous with the URI of the BNF. The drawback is that it has not yet been enriched with the new form "Philharmonie de Paris". So, if this poses a problem, I think that the best option is to use the VIAF URI.

**Comment by rtroncy** [comment]
I will slightly differ to be more consistent with our current policy, i.e. mint a new URI in our namespace which will be sameAs with many other identifiers. This will follow as well the new Europeana policy. Hence, we will get something like:
```
<http://data.doremus.org/event/f887237f-239e-3844-b1be-f328763a00e2>
    a         efrbroo:F42_Representative_Expression_Assignment ;
    efrbroo:R44_carried_out_by  <http://data.doremus.org/organization/Philharmonie_de_Paris> .

<http://data.doremus.org/organization/Philharmonie_de_Paris>
    owl:sameAs   <http://www.isni.org/isni/0000000121834950> ;
    owl:sameAs   <http://catalogue.bnf.fr/ark:/12148/cb16651244g> ;
    owl:sameAs   <http://viaf.org/viaf/315254866> ;
    owl:sameAs   <http://dbpedia.org/resource/Philharmonie_de_Paris> ;
    owl:sameAs   <http://www.wikidata.org/entity/Q3378907> .
```

Note that DBpedia multi-type this entity as an organization, but also as a place/location, as a museum, as a building and as an architectural structure. Wikidata also consider that interesting statements are attached to the building (architect is Jean Nouvel, etc.)

**Comment by pasqLisena** [comment]
@rtroncy following your proposal, i will suggest to not include the isni in the sameAs list, because it identify the Cité Musique. BnF link suggest that it is a 'Regroupement' of PP, that has not ISNI (at least for now).

**Comment by rtroncy** [comment]
Ah ah! We are talking about granularity of description :-)
 - ```<http://catalogue.bnf.fr/ark:/12148/cb16651244g>``` identifies the new Philharmonie building open in 2015 and the old Cité de la Musique building
 - DBpedia and Wikidata do not have this granularity but I suspect they mean the same thing
 - ```<http://www.isni.org/isni/0000000121834950>``` identifies indeed the old Cité de la Musique building, but whether they plan to mint a new URI for the newest building or to simply update this description, I don't know ... Philharmonie should now (or request an update?)

**Comment by ccecconi** [comment]
Hello. I agree with Pasquale. I think it's better not to use "same as". It isn't exactly the same entity. Wikipedia contains two articles : one with the label "Cité de la musique" and an other one with "Philharmonie". That's right the definition of the first one is very large but, still, there are two articles.

**Comment by pasqLisena** [comment]
So basically I am going to put the `sameAs` only if the landing page of the link have 'Philarmonie de Paris' as title.
