### ISSUE TITLE
[BnF] Artists mapping 

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#30]
**BUG!** We are parsing the records about _Persons_ as they are _Works_.
Just one example: http://data.doremus.org/expression/1df26713-02eb-3025-8840-65c5df50c5b0

What to do:
- [x] distinguish persons and TUMs
- [ ] decide a model for the persons (according to #27, @rtroncy is going to propose one)
- [ ] parse the persons records properly using the same uri generation policy described [here](https://github.com/DOREMUS-ANR/marc2rdf/issues/27#issuecomment-266737214)

**Comment by pasqLisena** [comment]
I produced a quick temporary parsing and mapping of artists, in order to have some information to visualize. These are examples of what it is currently produced:

```ttl
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix ecrm:  <http://erlangen-crm.org/current/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix efrbroo: <http://erlangen-crm.org/efrbroo/> .
@prefix mus:   <http://data.doremus.org/ontology#> .

<http://data.doremus.org/artist/4078845b-13e6-34e7-b06d-b4e1668712f1>
        a                           ecrm:E21_Person ;
        ecrm:P131_is_identified_by  "Franz Gehring" ;
        ecrm:P98i_was_born          "1838" ;
        owl:sameAs                  <http://catalogue.bnf.fr/ark:/12148/cb10215859s> , 
                                              <http://isni.org/isni/0000000046172511> .

<http://data.doremus.org/artist/74db7ade-74c2-3946-a758-0123f6a657a1>
        a                           ecrm:E21_Person ;
        ecrm:P131_is_identified_by  "Benjamin Franklin"@eng ;
        ecrm:P98i_was_born          "1706" ;
        owl:sameAs                  <http://catalogue.bnf.fr/ark:/12148/cb119034658> .

```

**Comment by pierrechoffe** [comment]
If this can be of any help, I had summed up in a schema the classes and properties used to describe a person in CRM / FRBRoo : 
https://drive.google.com/open?id=0B4s5dBwAmhJsZmxSaGR5UjRwNmM
The example is imaginary. The person was Russian by birth and became Ukrainian after the dissolution of USSR.

**Comment by pasqLisena** [comment]
This is enough (at least for now)
