### ISSUE TITLE
Integrate the MODS of Catalogs in the conversion

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#33]
- [x] Wait for the realisation of the MOD -- [follow it](https://github.com/DOREMUS-ANR/knowledge-base/issues/21)
- [x] Implement

**Comment by pasqLisena** [comment]
@pierrechoffe can you confirm that this is the expected format of a catalog?

```turtle
<http://data.doremus.org/expression/3ade71c3-eb15-3268-9fd5-48343a120e9c/catalog/1>
        a                             mus:M1_Catalogue_Statement ;
        mus:U40_has_catalogue_name    <http://data.doremus.org/vocabulary/catalog/009> ;
        mus:U41_has_catalogue_number  "1080" ;
        ecrm:P3_has_note              "BWV 1080" .
```

`<http://data.doremus.org/vocabulary/catalog/009>` corresponds to [this resource](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/catalog.ttl#L272).

**Comment by pierrechoffe** [comment]
Yes I confirm :)
Nice work btw !
