### ISSUE TITLE
[BnF] Implement mapping rules for BnF casting

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#35]
The mapping rules that we are now using for casting in BnF TUM are not correct.

We need to implement the lines 100-102 on the [mapping table](https://drive.google.com/drive/folders/0B4s5dBwAmhJsR2w4emw2X01xcGc) on Google Drive.

**Comment by rtroncy** [comment]
Furthermore, keep using the information in the "sous-zone 144 $b" of the notice and represent it as a simple textual note attached to the casting.

Assigning this issue to @pasqLisena but feel free to unassign :-)
