### ISSUE TITLE
[BNF] catalog names replaced by instrument labels

### ISSUE THREAD

**Issue by manoach** [DOREMUS-ANR/marc2rdf#37]
In the triple store, for some works of the BNF (I'm not sure for the works of the PP), the catalog name is replaced by the prefLabel of an instrument.

Here, some examples:

- [ ] [Tantum ergo](http://data.doremus.org/expression/c1bba4fb-aa96-3a59-b598-b9b83aac6a64)
Where the [catalog](http://data.doremus.org/describe/?url=nodeID%3A%2F%2Fb87609) name "D" is replaced by the prefLabel of the [instrument](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mop-diabolo.ttl#L2636) in mop-diabolo vocabulary.

- [ ] Another [work](http://data.doremus.org/expression/1f91d216-0bfc-3340-9dcb-51880fea07b6)
Where the [catalog](http://data.doremus.org/describe/?url=nodeID%3A%2F%2Fb106319) name "D" is replaced by the prefLabel of the [instrument](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mop-diabolo.ttl#L2636) in mop-diabolo vocabulary.

- [ ] Another [work](http://data.doremus.org/expression/7728eae4-85f0-37b4-9b5d-ced437542de6)
Where the [catalog](http://data.doremus.org/describe/?url=nodeID%3A%2F%2Fb14388) name "D" is replaced by the prefLabel of the [instrument](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/mop-diabolo.ttl#L2636) in mop-diabolo vocabulary.

It seems that the converter matches the name of the catalog with the altLabel of the instrument.

**Comment by pierrechoffe** [comment]
...and a lot more, [see the list](http://data.doremus.org/describe/?url=http%3A%2F%2Fdata.doremus.org%2Fvocabulary%2Fdiabolo%2Fmop%2Fdrums)

**Comment by rtroncy** [comment]
Can we also get rid off the blank nodes by creating a URI for the value of the ```mus:U40_has_catalogue_name``` property?

**Comment by pasqLisena** [comment]
I already realized what are you describing in this issue.
The problem is currently solved in marc2rdf and next release of data will not show this problem.
Thank you anyway for this report :)

> Can we also get rid off the blank nodes by creating a URI for the value of the mus:U40_has_catalogue_name property?

Also this is already in the code :) I also working for removing blank nodes at all.
