### ISSUE TITLE
BnF TUM mapping update

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#39]
A revision of mapping for TUM is available on Google Drive:
https://drive.google.com/file/d/0B4s5dBwAmhJsNXQxV3RxRnVLamc/view?usp=sharing

We should check it and align the implementation of the converter.

**Comment by pasqLisena** [comment]
@pierrechoffe It is not clear for me if the property `R40 has representative expression` should be replaced by `U38 has descriptive expression`

**Comment by pierrechoffe** [comment]
@pasqLisena the new mapping should be ready soon. Regarding R40 / U38, the modelling group decided that U38 would be the default (meeting 2016-11-03).

**Comment by pasqLisena** [comment]
> the new mapping should be ready soon
It means that the spreadsheet is currently work in progress?

> the modelling group decided that U38 would be the default (meeting 2016-11-03)
But there are cases for which we should use `R40`? I mean real cases on the data, the abstract meaning is clear for me.

**Comment by pierrechoffe** [comment]
> It means that the spreadsheet is currently work in progress?
The modifications/additions in the spreadsheet are the first step, next step is BnF adding the rules.
On my side (modifications/additions), I still have a few things to check, it's a huge overhaul !

>there are cases for which we should use R40?
We will not use R40 anymore because we do not have any easy way to decide whether we are on the U38 or R40 side. So we will use U38 only. If someone somewhere has the possibility to distinguish both use cases, he could use both properties, therefore the model does not say that R40 should be avoided. But as far as we are concerned, we will use U38 only.

**Comment by pasqLisena** [comment]
I see that the `M45_Descriptive_Expression_Assignment` have a connection with `F15 Complex Work` of the type `P140 assigned to` -- [slides](https://drive.google.com/file/d/0B4s5dBwAmhJsVGFrVi12RkJjUGs/view?usp=sharing).

However in CIDOC that property is called [`P140 assigned attribute to`](http://erlangen-crm.org/current/P140_assigned_attribute_to). What should we do?

**Comment by pierrechoffe** [comment]
Definitely use `P140 assigned attribute to`, I will correct the slide(s)

**Comment by pasqLisena** [comment]
Another thing, now we should apply U3 and U4 both to F22 and F14?

**Comment by pierrechoffe** [comment]
You mean U4 and U5 ?
Now you can apply them to both F22 and F14, but you don't have to. F22 is the preferred option, we should not use F14. Since F14 and F22 are technically equivalent, the idea is to have all the info on one node (F22).

**Comment by pasqLisena** [comment]
> Since F14 and F22 are technically equivalent, the idea is to have all the info on one node (F22).

Should I keep it on F14 for compatibility reasons? (apart from overture, also @delahousse is working on these things)

**Comment by pierrechoffe** [comment]
Sure, we can apply to both F22 and F14 (but not _instead of_ F22... applying only to F14 would not be a good idea).

**Comment by pasqLisena** [comment]
Another review has been released:
https://drive.google.com/open?id=0B55dxt4olm-DR1VxbVh3Y05rdTA

The converter needs an update

**Comment by pasqLisena** [comment]
Closed with  08e8c22
