### ISSUE TITLE
Data with apostrophe '

### ISSUE THREAD

**Issue by fernanev** [DOREMUS-ANR/marc2rdf#4]
In the xml files, some data have apostrophe, and the ContentHandler doesn't save all the string, it split it each time it finds one. As it is written the function [`characters`](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/src/org/doremus/marc2rdf/bnfparser/MarcXmlHandler.java#L95) if one part of the data is splitted, it will not enter again to append the other parts because bDATA is not true anymore.

In order to keep the functionality of the program as is but at the same time avoid this problem, I suggest change the function as:
```
public void characters(char[] ch, int start, int length) throws SAXException {
 if (bDATA) {
	    	buffer.append(new String(ch, start, length)); // RÃ©cupÃ©rer le contenu de la balise "data"
	    }
  }
```
and add in [`startElement`](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/src/org/doremus/marc2rdf/bnfparser/MarcXmlHandler.java#L52) a re-initialization of the variable: `bDATA = false;`

**Comment by manowb** [comment]
Hi Eva,

Thank you for the remark.  Could you give me an example, please, of a value that the program doesn't retrieve and split it?

Thank you again ...

**Comment by pasqLisena** [comment]
I anticipate Eva with "Il Ritorno d'Ulisse in patria":

- input https://drive.google.com/file/d/0B5aAYp6pCokXWllGWkhMT1A5UDg/view?usp=sharing
`<subfield code="a" Barre="3">Il ritorno d&apos;Ulisse in patria</subfield>`

- output: https://drive.google.com/file/d/0B5aAYp6pCokXcEQxbFNPYkdKSGM/view?usp=sharing
`      cidoc-crm:P102_has_title
              "Il ritorno d" ;
`

**Comment by manowb** [comment]
Thank you Pasquale for your reply. I just checked and it is an encoding problem:

- In the source file (when I downloaded it) "Il Ritorno d'Ulisse in patria" is written like this "Il ritorno d&apos;Ulisse in patria" and effectively the program split it and give us just "Il ritorno d".

- I tried to modify in the same file "Il ritorno d&apos;Ulisse in patria" with "Il Ritorno d'Ulisse in patria" and the program gave the right title "Il Ritorno d'Ulisse in patria" (with apostrophe)

<img width="639" alt="sans titre" src="https://cloud.githubusercontent.com/assets/5494373/14534731/be049e7c-026a-11e6-9824-82e5f7163eb0.png">

**Comment by manowb** [comment]
Thank you Pasquale for your reply. I just checked and it is an encoding problem:

In the source file (when I downloaded it) "Il Ritorno d'Ulisse in patria" is written like this 
<img width="503" alt="sans titr" src="https://cloud.githubusercontent.com/assets/5494373/14534825/250e1008-026b-11e6-816c-ff86c562a4c1.png">
 and effectively the program split it and give us just "Il ritorno d".

I tried to modify it in the same file with "Il Ritorno d'Ulisse in patria" and the program gave the right title "Il Ritorno d'Ulisse in patria" (with apostrophe)

<img width="639" alt="sans titre" src="https://cloud.githubusercontent.com/assets/5494373/14534843/3d3ce398-026b-11e6-8dbd-f29f5074f2e5.png">

**Comment by pasqLisena** [comment]
Yes, I see. However, I have taken these files from the [Google Drive folder](https://drive.google.com/drive/folders/0B5aAYp6pCokXUm14dk12TEpaSDA), so I imagine that our source files will be in that format, will they be not? If it is so, we should support them.

**Comment by manowb** [comment]
Hi @pasqLisena @fernanev ,

Sorry for the deley, I was busy :/ ....... To answer your question, yes, the source files are in that format. I think that it would be better if the converter takes into account the different encoding forms. So, my question is : Is Eva's proposal transforms "&apos;" in an "apostrophe"? Do we have "Il ritorno d'Ulisse in patria" or "Il ritorno dUlisse in patria" (without apostrophe)? 

I'm sorry again for the deley ...

Thank you :)

**Comment by manowb** [comment]
Hi @pasqLisena @fernanev ,

Sorry for the deley, I was busy :/ ....... To answer your question, yes, the source files are in that format. I think that it would be better if the converter takes into account the different encoding forms. So, my question is : Is Eva's proposal transforms "& a p o s ;" in an "apostrophe"? Do we have "Il ritorno d'Ulisse in patria" or "Il ritorno dUlisse in patria" (without apostrophe)?

I'm sorry again for the deley ...

Thank you :)

**Comment by fernanev** [comment]
Hi @manowb ,

With that change we get "Il ritorno d'Ulisse in patria", with apostrophe.

If it is ok for you, I will modify the code :)

**Comment by manowb** [comment]
Ok @fernanev you can modify it .... Thank you again :)
