### ISSUE TITLE
[PP] Give an URI to periods

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#40]
Historical periods should have an URI in order to avoid blank and duplicate nodes in the graph.

[Query](http://data.doremus.org/sparql?default-graph-uri=http%3A%2F%2Fdata.doremus.org%2Fphilarmonie&query=select+distinct+%3Flabel+COUNT%28%3Fs%29+where+%7B+%0D%0A%3Fs+a+ecrm%3AE4_Period%3B%0D%0Aecrm%3AP1_is_identified_by+%3Flabel%0D%0A%7D+GROUP+BY+%3Flabel&format=text%2Fhtml&timeout=0&debug=on):
```sparql
select distinct ?label COUNT(?s) where { 
  ?s a ecrm:E4_Period;
      ecrm:P1_is_identified_by ?label .
} GROUP BY ?label
```

**Comment by rtroncy** [comment]
Proposal: ```<http://data.doremus.org/period/UUID>```. This can also be aligned with dbpedia, e.g. ```<http://dbpedia.org/resource/17th_century>```

**Comment by pasqLisena** [comment]
What about `<http://data.doremus.org/period/17th_century>` ?

**Comment by rtroncy** [comment]
Why not! But would you be able to name any period you may encounter in the data? It is easy when we talk about plain century but in the data, I can see "20 ème siècle - 2 ème moitié" or "Périodes historiques" or "Révolution française". In short, I think it would be better to provide a UUID to identify the period and add a proper label and sameAs links to wikipedia/dbpedia entities when they exist
