### ISSUE TITLE
Problem in parsing catalog number

### ISSUE THREAD

**Issue by manoach** [DOREMUS-ANR/marc2rdf#41]
For works whose catalog is composed of 3 strings separated by a white space, the parser retrieves only the first 2 strings as name and catalog number respectively.

[Here](http://data.doremus.org/describe/?url=nodeID%3A%2F%2Fb21712) is an example:

![image](https://cloud.githubusercontent.com/assets/5494373/23459557/24fb7160-fe81-11e6-82d1-f6f803f64311.png)

Note that the mapping rules to extract the name and the catalog number are:

```
1.  Le nom du catalogue: Prendre la chaîne de caractères alphabétiques avant l'espace.

2. Le numéro du catalogue: chaîne de caractères numériques (chiffres) ou alphanumériques (lettre(s) et chiffres) après l'espace.
```

So, in this example, "4" must appear in the catalog number but I'm wondering if "VIId" should appear in the catalog name rather than the catalog number ?

**Comment by manoach** [comment]
> but I'm wondering if "VIId" should appear in the catalog name rather than the catalog number ?

Martine answered me : "VIId is part of the catalog number."

**Comment by pierrechoffe** [comment]
to be precise, rule nr. 2 should be : 
```
2. Le numéro du catalogue: chaîne de caractères numériques (chiffres) ou alphanumériques (lettre(s) et chiffres, y compris espaces les séparant) après le premier espace.
```
or shorter : 
```
2. Le numéro du catalogue: tout ce qui suit le premier espace
```

**Comment by pasqLisena** [comment]
I am doing a full conversion right now, I fix this immediately

**Comment by pasqLisena** [comment]
This is the new result of the catalog parsing:

```turtle
<http://data.doremus.org/expression/79d3427c-b116-3ebd-8661-f045e47b6551>
        a                    efrbroo:F22_Self-Contained_Expression ;
        rdfs:label           "Concertos" ;
        mus:U11_has_key      <http://data.doremus.org/vocabulary/key/d> ;
        mus:U12_has_genre    <http://data.doremus.org/vocabulary/iaml/genre/co> ;
        mus:U13_has_casting  <http://data.doremus.org/expression/79d3427c-b116-3ebd-8661-f045e47b6551/casting/1> ;
        mus:U16_has_catalogue_statement
                <http://data.doremus.org/expression/79d3427c-b116-3ebd-8661-f045e47b6551/catalog/Hob_VIId_4> ;
        mus:U70_has_title    "Concertos" ;
        dcterms:publisher    <http://data.doremus.org/organization/BnF> .

<http://data.doremus.org/expression/79d3427c-b116-3ebd-8661-f045e47b6551/catalog/Hob_VIId_4>
        a                             mus:M1_Catalogue_Statement ;
        rdfs:label                    "Hob VIId 4" ;
        mus:U40_has_catalogue_name    "Hob" ;
        mus:U41_has_catalogue_number  "VIId 4" ;
        ecrm:P3_has_note              "Hob VIId 4" .
```

**Comment by manoach** [comment]
Thank you @pasqLisena :)

**Comment by pierrechoffe** [comment]
Voir un exemple intéressant [à la BnF](http://catalogue.bnf.fr/ark:/12148/cb162396343) : FRBNF16239634
