### ISSUE TITLE
[BnF] Different composer's name appears as different composers

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#42]
### Problem

In some cases, a work can have **different composers** (so, different `P9_consists_of` > `E7_Activity`).
Example: http://data.doremus.org/event/fcc136b1-4b9d-3eec-b469-3cafe05c74e5

In other cases, the MARC file mentions instead **different names for the same composer**. This happens in particular when the original name of a composer is written in a different alphabet.
Example: http://data.doremus.org/event/0405e2e1-79b4-3b94-886b-980021858344

Query for retrieving [other examples](http://data.doremus.org/sparql?default-graph-uri=http%3A%2F%2Fdata.doremus.org%2Fbnf&query=SELECT+%3Factivity+%3Fperson+SAMPLE%28%3Fcomposer%29%0D%0AWHERE+%7B%0D%0A++%3FexpCreation+ecrm%3AP9_consists_of+%3Factivity+.%0D%0A++%3Factivity+ecrm%3AP14_carried_out_by+%3Fperson+.%0D%0A++%3Fperson+ecrm%3AP131_is_identified_by+%3Fcomposer+.%0D%0A++%7B%0D%0A++SELECT+%3FexpCreation%0D%0A++WHERE+%7B+%3FexpCreation+ecrm%3AP9_consists_of+%3Factivity+%7D%0D%0A++GROUP+BY+%28%3FexpCreation%29%0D%0A++HAVING+%28+COUNT%28%3Factivity%29+%3E+1+%29%0D%0A++LIMIT+100%0D%0A++%7D%0D%0A%7D%0D%0AGROUP+BY+%3Factivity+%3Fperson%0D%0AORDER+BY+%3Factivity&format=text%2Fhtml&timeout=0&debug=on):
```sparql
SELECT ?activity ?person SAMPLE(?composer)
WHERE {
  ?expCreation ecrm:P9_consists_of ?activity .
  ?activity ecrm:P14_carried_out_by ?person .
  ?person ecrm:P131_is_identified_by ?composer .
  {
  SELECT ?expCreation
  WHERE { ?expCreation ecrm:P9_consists_of ?activity }
  GROUP BY (?expCreation)
  HAVING ( COUNT(?activity) > 1 )
  LIMIT 100
  }
}
GROUP BY ?activity ?person
ORDER BY ?activity
```

### Workflow

- [x] Double check in the MARC if the BnF identifier of the author is declared
- [ ] Use it to distinguish different composers
- [x] Consider if it should be used to generate the composer URI  ([the way in which we are generating it now](https://github.com/DOREMUS-ANR/marc2rdf/issues/27#issuecomment-266748215) grant an automatic interlinking with PP data and not only)

**Comment by pierrechoffe** [comment]
Maybe the different spellings of the author name should be in a skos file ? with one preferred and the others as alternate ?

**Comment by rtroncy** [comment]
We should not mix up problems that come from the conversion side versus challenges that belong to instance matching. Resolving that 2 entities with different spelled names actually refer to the same person is the business of the instance matching task (they have tons of efficient methods for this, cc @kgtodorov).

On the other hand, what is relevant for the conversion side is to make sure we properly use id/idref from the MARC files when those are provided.

**Comment by pierrechoffe** [comment]
@rtroncy @pasqLisena 
There is a general problem with names, with degrees of complexity: the smallest (?) complexity is spelling, the greatest is pseudonyms.
To solve this, only unique ids can help (ISNI, VIAF...), and BnF has a list of equivalent names that can help the instance matching process (that's why I was talking about a skos file).
But the problem raised by Pasquale is that there appears to be 2 (or more) different composers (cf. Rachmaninov) where actually there's only one, i.e. the conversion takes a string, not a uri, am I right?

**Comment by pasqLisena** [comment]
> But the problem raised by Pasquale is that there appears to be 2 (or more) different composers (cf. Rachmaninov) where actually there's only one, i.e. the conversion takes a string, not a uri, am I right?

I confirm. The fact is that in the MARC file, 2 "composer fields" could refers to 2 composers for real (so 2 activities, 2 persons, etc.) OR 2 names for the same composer (1 activity, 1 person).

> We should not mix up problems that come from the conversion side versus challenges that belong to the instance matching task.

I agree, btw it is very important to have 1 activity in the case it is required, and if the MARC file contain the BnF id, we can get it fast.

**Comment by rtroncy** [comment]
> I confirm. The fact is that in the MARC file, 2 "composer fields" could refers to 2 composers for real (so 2 activities, 2 persons, etc.) OR 2 names for the same composer (1 activity, 1 person).

and do you have a way to distinguish those 2 cases from the MARC file?

**Comment by pasqLisena** [comment]
## MARC file contents

* Different composers

```xml
<datafield tag="100" ind1=" " ind2=" ">
	<subfield code="3">13930222</subfield>
	<subfield code="w"> 0  b     </subfield>
	<subfield code="a">Boyer</subfield>
	<subfield code="m">Jean</subfield>
	<subfield code="d">1901-1965</subfield>
</datafield>
<datafield tag="100" ind1=" " ind2=" ">
	<subfield code="3">14041266</subfield>
	<subfield code="w"> 0 2b     </subfield>
	<subfield code="a">Verdun</subfield>
	<subfield code="m">Henri</subfield>
	<subfield code="d">1895-1977</subfield>
</datafield>
```

* Same composer, different names
```xml
<datafield tag="100" ind1=" " ind2=" ">
	<subfield code="3">13898765</subfield>
	<subfield code="w">.0 .barus.</subfield>
	<subfield code="a">Rahmaninov</subfield>
	<subfield code="m">Sergej Vasil&apos;evič</subfield>
	<subfield code="d">1873-1943</subfield>
</datafield>
<datafield tag="100" ind1=" " ind2=" ">
	<subfield code="w"> 0  c     </subfield>
	<subfield code="a">Рахманинов</subfield>
	<subfield code="m">Сергей Васильевич</subfield>
	<subfield code="d">1873-1943</subfield>
</datafield>

```

We use the subfield `w` only for extract the language (in the example only `rus` for Rahmaninov).
**Q1:** What is the meaning for that `b`, `2b`, `c` ?
I see that if I consider only the 
**Q2:**

**Comment by FLERESCHE** [comment]
Q1 : Voici la description du contenu du $w
pos. 01 : Valeur de la forme
0 = forme savante ou à valeur internationale
pos. 03 : Type de nom de personne
# (blanc) ou . (point) = non précisé ou sans objet, i.e. nom d'état civil
1 =nom d'alliance
2 = pseudonyme
3 = pseudonyme collectif
4 = nom en religion
pos. 04 : Ecriture de la forme
b = latin 
c = cyrillique
f = arabe
g = grec
h = hébreu
etc. La liste des codes est disponible dans la documentation du format INTERMARC sur le site de la BnF : http://www.bnf.fr/documents/intermarc_ref_ecritures.pdf
pos. 05 : Système de translittération utilisé
# (blanc) ou . (point) = pas de translittération
a = système ISO de translittération complète
b = système ISO de translittération simplifiée (hébreu, arabe, etc.)
c = système ISO de romanisation (chinois, etc.)
d = système propre à la BnF
m = systèmes multiples
u = romanisation sans système connu
x = autre système de translittération à valeur internationale (japonais, etc.)
pos. 06-08 = Langue de la forme

Q2 : OUI, il faut prendre en considération la présence de la sous-zone $3 (identifiant de la notice d'autorité) pour déterminer si c'est un autre auteur ou au contraire 2 formes parallèles (dans des écritures différentes) du nom d'une même personne.
C'est le $3 qui indique la présence d'un lien vers une notice d'autorité PEP (personne physique), donc vers une personne différente.

**Comment by FLERESCHE** [comment]
Moreover, PP and BnF have different ids and "preferred tranlistteration" for artists, so an instance matching process should be performed after the conversion.

La BnF a fourni toutes ses notices d'autorité personnes et collectivités liées aux notices bibliographiques.
Ces notices d'autorité contiennent l'identifiant ISNI de la personne ou de la collectivité.
Par ailleurs, elles contiennent sans doute en variantes (zones 400) les formes avec d'autres translittérations que la translittération ISO utilisée dans le point d'accès privilégié (zone 100).
Il me semble que le rapprochement des compositeurs (et plus tard des interprètes) doit se faire d'abord à travers l'identifiant ISNI qui va gérer les multiples formes du nom et les variantes de noms. S'il n'y a pas d'ISNI, il faut comparer toutes les formes 100 et 400 des notices PEP de la BnF avec les formes de la Philharmonie. Même démarche pour les collectivités (orchestres, etc.) quand on traitera les notices bibliographiques.

**Comment by pasqLisena** [comment]
Thanks @FLERESCHE.

Basically we should take in account the content of the field `100` **only if the subfield `$3` exists**.
I suggest to continue to use the **same system of generation UUID**:
* for most of the authors, the name is the same for all institution, so we will have only [1 URI](http://data.doremus.org/sparql?default-graph-uri=&query=select+DISTINCT+*+where+%7B+%0D%0A%3Fs+a+ecrm%3AE21_Person%3B+%0D%0Afoaf%3Asurname+%22Mozart%22%3B+%0D%0Afoaf%3AfirstName+%22Wolfgang+Amadeus%22%3B%0D%0Afoaf%3Aname+%3Flabel%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on)
* for some, different translitteration will generate different [persons](http://data.doremus.org/sparql?default-graph-uri=&query=select+*+where+%7B+%3Fs+a+ecrm%3AE21_Person%3B+foaf%3Aname+%3Flabel.+FILTER+%28REGEX%28str%28%3Flabel%29%2C+%27manino%27%29%29+%7D&format=text%2Fhtml&timeout=0&debug=on) that will be interlinked later
