### ISSUE TITLE
Trivial errors on parsing of casting

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#45]
See this [query](http://data.doremus.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+*%0D%0AWHERE+%7B%0D%0A++%3Fperformance+ecrm%3AP9_consists_of+%3Fpart+.%0D%0A++%3Fpart+mus%3AU1_used_medium_of_performance+%3Fmop%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on) for further information

```sparql
SELECT DISTINCT *
WHERE {
  ?performance ecrm:P9_consists_of ?part .
  ?part mus:U1_used_medium_of_performance ?mop
}
```

**Comment by rtroncy** [comment]
The MoP strings should be interlinked with the pivot controlled vocabulary as well, see also the [knowledge-base/issue 23](https://github.com/DOREMUS-ANR/knowledge-base/issues/23).

**Comment by pierrechoffe** [comment]
Why are there 2 clarinets for he second performance (http://data.doremus.org/performance/2b38d6d4-85d3-39c5-a49e-43c10304642a) when There is only one in the casting ? (http://data.doremus.org/describe/?url=http%3A%2F%2Fdata.doremus.org%2Fexpression%2Fab4f119b-d36a-337e-b3b4-f4a9b8c94042%2Fcasting%2F1%2Fdetail%2F1)

**Comment by pierrechoffe** [comment]
same for http://data.doremus.org/performance/c3f844cf-ebc1-37c4-a9f1-ed90228b2c82
