### ISSUE TITLE
Mapping of librettists

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#46]
In MARC files from both BnF and PP the information about the librettist is present.

Example: **Aida**
1. http://digital.philharmoniedeparis.fr/doc/CIMU/0758984 (field 701)
2. http://catalogue.bnf.fr/ark:/12148/cb13920545w.intermarc (field 322)

It is possible to extract this information from MARC files and map it to DOREMUS?

**Comment by pasqLisena** [comment]
For BnF, closed in  08e8c22

**Comment by ccecconi** [comment]
Ok for it. The information is in UNI100 : 700$4 or 701$4 (person associated with the function code "480". 
I just added a lign about it in the mapping : https://docs.google.com/spreadsheets/d/1OMq-JRks8ZSobSssMK83Iw_SlqgZcmlAy_3zZrwaLag/edit#gid=1964546468

**Comment by pasqLisena** [comment]
Closed in 3ca546fb64a7a8783347adce8e5942cb6742e18c
