### ISSUE TITLE
[PP] Oboe matching in MIMO

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#52]
In French, the string "**Hautbois**" is both singular and plural.

So in MIMO it compares as `prefLabel` of both:
* Oboe's family `"Oboes"@en` http://www.mimo-db.eu/InstrumentsKeywords/4164
* Oboe as instrument `"Oboe"@en` http://www.mimo-db.eu/InstrumentsKeywords/4232

Currently the matching goes to the first, while the second is the correct one normally.

Maybe we should implement a workaround for this.

**Comment by rtroncy** [comment]
> Maybe we should implement a workaround for this.

One heuristic could be: "always privilege the instrument over the family" when there are multiple match. Does it make sense?

**Comment by pasqLisena** [comment]
Yes, could be good
