### ISSUE TITLE
Implementation of mapping rules for Opus Number

### ISSUE THREAD

**Issue by pierrechoffe** [DOREMUS-ANR/marc2rdf#55]
As can be seen from [the results](http://data.doremus.org/sparql?default-graph-uri=&query=SELECT+*+%0D%0AWHERE+%7B+%0D%0A%3Fexpression+dct%3Aidentifier+%3Fid%3B+%0D%0Aprov%3AwasDerivedFrom+%3Fsource%3B+%0D%0Amus%3AU17_has_opus_statement+%2F+mus%3AU42_has_opus_number+%3Fop+.%0D%0Afilter+%28%3Fop+%3E+%221000%22%29.%0D%0A%7D+LIMIT+1000&format=text%2Fhtml&timeout=0&debug=on) of following queries, the extraction of opus numbers and sub-numbers can be very complex, due to inconsistencies in the sources.
```sparql
SELECT * 
WHERE { 
 ?expression dct:identifier ?id; 
               prov:wasDerivedFrom ?source; 
               mus:U17_has_opus_statement / mus:U42_has_opus_number ?op .
 filter (?op > "1000").
} LIMIT 100
```
The extraction of sub-numbers works, but can also reveal [lots of inconsistencies](http://data.doremus.org/sparql?default-graph-uri=&query=SELECT+*+%0D%0AWHERE+%7B+%0D%0A%3Fexpression+dct%3Aidentifier+%3Fid%3B+%0D%0Aprov%3AwasDerivedFrom+%3Fsource%3B+%0D%0Amus%3AU17_has_opus_statement+%2F+mus%3AU43_has_opus_subnumber+%3Fop+.%0D%0Afilter+%28%3Fop+%3E+%22100%22%29+.%0D%0A%7D+LIMIT+1000&format=text%2Fhtml&timeout=0&debug=on).
```sparql
SELECT * 
WHERE { 
?expression dct:identifier ?id; 
prov:wasDerivedFrom ?source; 
mus:U17_has_opus_statement / mus:U43_has_opus_subnumber ?op .
filter (?op > "100") .
} LIMIT 100
```
This point should be discussed with the WG2 on Friday 9 June.

**Comment by pasqLisena** [comment]
Groups:
- Corrects, no fix need
   - `105a` , `203 bis`, `7/1`, etc.
- Trivials, needs an extension of current rules:
   - different string `n°`, `no°`, `N.`, `no.`, `Op.`, `op`, `Opus`, etc.
   - assence of comma `,`
- Exception in syntax
  - `[Op. 3, no 2]`, `partie 2`, `livre 1`
- Ranges
  - `5 et 6`, `1-3`, `4 à 8`
- Presence of the string `posthume`/`post.`
- Different content in `144$p`
  - `WoO 16`, `Do majeur`, `L 54`

**Comment by pierrechoffe** [comment]
@pasqLisena actually when considering whether change is needed (at the source or implementation level), we have to make a clear distinction between opus numbers and opus sub-numbers. For instance, "7/1" is acceptable (although highly improbable) at the sub-number level, but _**not**_ at the number level because in this case this is clearly an Op. 7, no 1 => 1 is the sub-number.

I agree with the other groups of errors, which btw aren't necessarily errors but sometimes just points we have to agree upon (e.g. how to define ranges) or to take as they are (posthume is definitely a correct value for opus)

**Comment by pasqLisena** [comment]
As decided in the modelling group, we are not going to fix that problems.
I extended/applied a fix that we already had for the philharmonie, in order to fix at least the "trivial" ones.
