### ISSUE TITLE
Representation of time

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#56]
From a [debate](https://docs.google.com/document/d/1YeeziwYhZKPr0eykwYmD_yrU1Wk4dlkV4FUrjCSpC8Y/edit?disco=AAAABOu-x7k) started after some modelling doubts, is clear the need for a new way to describe times.

In particular `ecrm:P79_beginning_is_qualified_by` (and `ecrm:P80_end_is_qualified_by`) relates actually to a "qualification" of the date information, the nature of which can be certainty, precision, source (e.g. "date approximative"). So we should stop to use them as we do today.

Because there is no special property in eFRBRoo for the start and end of a Time Span,
we should rely on other ontologies.

I propose the [**Timeline Ontology**](http://motools.sourceforge.net/timeline), that comes from the more popular [Time Ontology](https://www.w3.org/TR/owl-time), to which the MusicOntology team added some simplifications.

How we model Time Spans **today**:
```turtle
<http://data.doremus.org/performance/4db95574-8497-3f30-ad1e-f6f65ed6c896/time>
    a ecrm:E52_Time-Span ;
    rdfs:label "1939-08-05/1939-08-30" ;
    ecrm:P79_beginning_is_qualified_by "1939-08-05"^^xsd:date ;
    ecrm:P80_end_is_qualified_by "1939-08-30"^^xsd:date .
```
How it can be in the **future**:

```turtle
<http://data.doremus.org/performance/4db95574-8497-3f30-ad1e-f6f65ed6c896/time>
    a ecrm:E52_Time-Span, tl:Interval;
    rdfs:label "1939-08-05/1939-08-30" ;
    tl:start "1939-08-05"^^xsd:date;
    tl:end "1939-08-30"^^xsd:date.
```
Moreover we can use P79 and P80 as they are intended to be, so we can have these kind of values:

|source data|date in the rdf|qualified by|
|-----|-----|-----|
|1983|1983|not specified|
|1983?|1983|`uncertain`|
|198.|1980|`precision at decade`|
|19..|1900|`precision at century`|

Please review this. @rtroncy @pierrechoffe @delahousse

**Comment by delahousse** [comment]
+1 for this proposal
has it been approved by the modelisation group ?  should I import TimeLine
ontology into Doremus ?

Jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data, Semantic Web, Knowledge
engineering
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55 <06%2001%2022%2048%2055>
skype jean.delahousse

2017-07-25 15:47 GMT+02:00 Pasquale Lisena <notifications@github.com>:

**Comment by pasqLisena** [comment]
> has it been approved by the modeling group ?

I think this is out of the scope of the DOREMUS model, it is just a thing that we need in the data.
I neither see the need for importing it in our ontology

**Comment by delahousse** [comment]
ok

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data, Semantic Web, Knowledge
engineering
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2017-08-28 12:20 GMT+02:00 Pasquale Lisena <notifications@github.com>:

**Comment by pasqLisena** [comment]
Maybe related: https://www.w3.org/blog/news/archives/6477
Going to give it a look

**Comment by rtroncy** [comment]
Right, this is what I just wrote in the google doc (CR of the modeling group).

I agree to use the ecrm properties P79 and P80 as they are intended to be used, i.e. to qualify the precision of the date/time. In this sense, the value of those properties will be literal such as "uncertain", "precision at decade", "precision at century". Is there an exhaustive list of such values?

For actually specifying the start / end time, we should use the [new Time Ontology](https://www.w3.org/TR/owl-time/). The namespace to use is ```http://www.w3.org/2006/time#``` while the namespace prefix recommended is ```time```.

A full example could be:
```turtle
<http://data.doremus.org/performance/4db95574-8497-3f30-ad1e-f6f65ed6c896/interval>
    a ecrm:E52_Time-Span, time:Interval;
    rdfs:label "1939-08-05/1939-08-30" ;
    time:hasBeginning [ a time:Instant; time:inXSDDate "1939-08-05"^^xsd:date];
    time:hasEnd [ a time:Instant; time:inXSDDate "1939-08-30"^^xsd:date].
```

**Comment by pasqLisena** [comment]
> Is there an exhaustive list of such values?

At least in the data, I can identify those 3 and eventually the `certainty` one. But they are DataProperties, so I will not create a mini vocabulary for them.

> The timeline ontology you referenced enables to save blank nodes (without going through the time:Instant) at the price of some expressivity.

Yes, indeed I like the idea of have a direct property like `tl:start "1939-08-05"^^xsd:date`. Are we sure we don't want to go for it? Which expressivity are we loosing in facts?

**Comment by rtroncy** [comment]
> At least in the data, I can identify those 3 and eventually the certainty one. But they are DataProperties, so I will not create a mini vocabulary for them.

+1

> Which expressivity are we loosing in facts?

Ah ah, this is the whole purpose of OWL Time :-) First, because of the timeline ontology, you're limiting to a single calendar, the Gregorian one. Imagine you want to use a different calendar, such as the Napoleon one. Look at the many use cases of OWL Time, the concept of a temporal reference system (TRS) as we do have for geography, etc.

**Comment by pasqLisena** [comment]
> Imagine you want to use a different calendar, such as the Napoleon one.

Ok, this is very far from our purposes 😄 
Anyway, let's go with Time Ontology for being compliant with standards.

**Comment by rtroncy** [comment]
Good, you can close this issue as well once the converter will be updated / cc @nicolasGuillouet so that you also take into account those changes in your new release of data
