### ISSUE TITLE
[PP] Keys with final dots

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#59]
Sometimes the keys end with a final dot.
Example: `"Fa majeur."@fr`
http://data.doremus.org/expression/b1d12b34-46a1-3d26-a6ad-efef75b1db7a/key/fa_majeur.

This prevents the converter to match with the controlled vocabulary.

**Comment by pierrechoffe** [comment]
To be fixed at the conversion level? The dot is an error (I mean: there is no situation where a dot would be required or meaningful).

**Comment by rtroncy** [comment]
Yes, the converter will handle this case, doing a specific parsing that will remove the last dot(s). But this shows that converting literals by controlled vocabularies helps to detect inconsistent annotation practices

**Comment by pasqLisena** [comment]
Already fixed
