### ISSUE TITLE
[PP] Works with different TUMs

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#61]
Some works have different TUMs. Example: 0804799.

Normally, the 1st one is exactly the same, the other ones "parts of" the main one. We generalise that are all of them are like this, waiting for a cleaning by the Philharmonie.

They will be connected by `has member`.
Only 1 `F15 Complex Work` will be instantiated.

- [x] Implement and produce an example
- [x] Validation by Cecile
- [ ] Correction and new export

**Comment by pasqLisena** [comment]
Query:
```sparql
SELECT DISTINCT * WHERE { 
 <http://data.doremus.org/work/fb36004d-4807-30a7-a9ec-7cc37482bfe7> efrbroo:R10_has_member / efrbroo:R9_is_realised_in ?expression.
  ?expression rdfs:label ?label
}
```

Navigable F15:
http://data.doremus.org/work/fb36004d-4807-30a7-a9ec-7cc37482bfe7 

@ccecconi please give a look :)

**Comment by rtroncy** [comment]
The [results of this query](http://data.doremus.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+*+WHERE+%7B+%0D%0A+%3Chttp%3A%2F%2Fdata.doremus.org%2Fwork%2Ffb36004d-4807-30a7-a9ec-7cc37482bfe7%3E+efrbroo%3AR10_has_member+%2F+efrbroo%3AR9_is_realised_in+%3Fexpression.%0D%0A++%3Fexpression+rdfs%3Alabel+%3Flabel%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on) also show 2 blank node identifiers for some expressions which should not be possible ... bug?

**Comment by pasqLisena** [comment]
Uploading issue. Do not care about them for now

**Comment by ccecconi** [comment]
In this case, in fact, the work record (UNI100) and the first TUM (AIC14) should be converted in only one F14 and F22. The AIC14 contains the variant titles and the uniform title of the F22. The UNI100 contains the "normal" title and the description of the F22. 
I modified the mapping to explain all that (https://docs.google.com/spreadsheets/d/1OMq-JRks8ZSobSssMK83Iw_SlqgZcmlAy_3zZrwaLag/edit#gid=1964546468).

It's right to convert the following TUMs (AIC14) in other F14 and F22.

**Comment by ccecconi** [comment]
In the example you sent to me, we can't see which F14 represents the whole work and which ones represents parts of this work. I spoke with Françoise about this. We think it would be better to have : 
- F15 (called A and which represents the whole work) _R10 has member_ F14 _has descriptive expression_ F22 (corresponding to UNI100 n° 0804799 and AIC14 n°0804786)
- F15 (called B and which represents a part of the work)  _R10 has member_ F14 R9 _is realised in__ F22 (corresponding to AIC14 n°0804792)
- F15 (called C and which represents a part of the work)  _R10 has member_ F14 R9 _is realised in__ F22 (corresponding to AIC14 n°0804789)
etc. 

and then : F14a has component F14b ; F14a has component F14c, etc.

**Comment by ccecconi** [comment]
We can speak about that on monday.

**Comment by pasqLisena** [comment]
> In this case, in fact, the work record (UNI100) and the first TUM (AIC14) should be converted in only one F14 and F22. The AIC14 contains the variant titles and the uniform title of the F22. The UNI100 contains the "normal" title and the description of the F22.

As the current status, this is just a change of the titles property, but we have a discussion in progress on this :)


> F15 (called A and which represents the whole work) R10 has member F14 has descriptive expression F22 (corresponding to UNI100 n° 0804799 and AIC14 n°0804786)
> F15 (called B and which represents a part of the work) R10 has member F14 R9 is realised in_ F22 (corresponding to AIC14 n°0804792)
> F15 (called C and which represents a part of the work) R10 has member F14 R9 is realised in_ F22 (corresponding to AIC14 n°0804789)

This is not clear, how many F15 are there?

Already present.
> F14a has component F14b ; F14a has component F14c, etc.

This should be added

**Comment by pasqLisena** [comment]
Waiting for answer on Part2

**Comment by rtroncy** [comment]
cc @ccecconi

**Comment by pierrechoffe** [comment]
Wouldn't it be easier for your queries to use FRBRoo's R5_has_component between the parent Expression and the children Expressions ? I know I have a tendency to repeat myself, but thinking and designing in terms of Expressions is much clearer than in terms of Works - and in this particular case it was conceived to be so already in the original FRBRoo.

**Comment by ccecconi** [comment]
Pasquale : I think we should have one couple F14+F22  for each TUM (except for the first one which should be concatenated with the UNI100 record). 
Normally we should also add a F15 for each TUM but maybe, to make it a little more simple, we could skip this for now and just keep one corresponding to the UNI100

**Comment by pierrechoffe** [comment]
Sure, I didn't say it was wrong, just FRBRoo's R5 would be so much simpler. For example, if you want to know the components of Préludes, Livre 1, with F14 you do 

F22/Livre1 --realises--> F14/Livre1 --has_component--> F14/Livre1/Prélude1 --is_realised_in--> F22/Livre1/Prélude1

With R5 you do 

F22/Livre1 --R5--> F22/Livre1/Prélude1

**Comment by pasqLisena** [comment]
@pierrechoffe we are using both, R5 between expressions and P148 between works

> Pasquale : I think we should have one couple F14+F22 for each TUM (except for the first one which should be concatenated with the UNI100 record).
Normally we should also add a F15 for each TUM but maybe, to make it a little more simple, we could skip this for now and just keep one corresponding to the UNI100

So, I consider this close
