### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#68]
Add those 2 licenses:
- https://www.etalab.gouv.fr/licence-ouverte-open-licence
- CC BY 4.0

Also in Itema3 and Euterpe.

**Comment by rtroncy** [comment]
Are you talking about licenses to attach to the data dump? Or licenses attached to the converter software?

For the data: ok for https://www.etalab.gouv.fr/licence-ouverte-open-licence + CC BY 4.0
For the software, let's go for Apache2

**Comment by pasqLisena** [comment]
Which class/property should be used for attaching license?
I mean, I do not want to declare that a certain work is licensed, but just that our data are licensed. Common practices?

**Comment by rtroncy** [comment]
The license should be attached to the dataset distribution. We need to provide a [DCAT](https://www.w3.org/TR/vocab-dcat/) description.

**Comment by pasqLisena** [comment]
Ok, I think this is similar to what we currently do with the [catalogue vocabulary](https://github.com/DOREMUS-ANR/knowledge-base/blob/master/vocabularies/catalogue.ttl#L10).

We need 1 DCAT for the whole dataset or 1 for each graph?

We need to attach every record to the DCAT ? Just the main ones (e.g. F22)? None of them?

**Comment by rtroncy** [comment]
I think we should do 1 DCAT for each graph (dump / dataset). The dataset will contain the description of many first class entities and among others F22

**Comment by pasqLisena** [comment]
So I guess something like this:

```turtle
<http://data.doremus.org/bnf> a dcat:Dataset ;
    rdfs:label "Graph BnF";
    rdfs:comment "Result of the conversion of MARC records coming from the Bibliothèque Nationale de France (BnF)";
    dct:accrualPeriodicity <http://dublincore.org/groups/collections/frequency/#freqirregular> ;
    dct:created "2016-07-01"^^xsd:date ;
    dct:issued "2016-07-01"^^xsd:date ;
    dct:creator <http://data.doremus.org/organization/DOREMUS> ;
    dct:modified "2018-03-16"^^xsd:date ; # to be added by converter
    dct:license <https://creativecommons.org/licenses/by/4.0/> ;
    dct:distribution <http://data.doremus.org/bnf/distribution/ttl> .


<http://data.doremus.org/bnf/distribution/ttl> a dcat:Distribution ;
    dcat:accessURL <https://github.com/DOREMUS-ANR/knowledge-base/tree/master/data/bnf> ;
    rdfs:label "Turtle distribution of Graph BnF" ;
    dcat:mediaType "text/turtle" .
```

Converted files will contain also:

```turtle
<http://data.doremus.org/bnf> dcat:records
     <http://data.doremus.org/expression/xxxxxx> ,
     <http://data.doremus.org/artist/xxxxxx> ,
     <http://data.doremus.org/event/xxxxxx> ,
      ...
```

**Q:** Which records should be directly linked?
- **A1.** All the ones that declare PROV data
    - e.g. for BnF records, f22, f28, f15, f14
    - e.g. for Itema3 records, f31
- **A2.** One for file:
    - e.g. for BnF records, f22
    - e.g. for Itema3 records, f31

**Comment by rtroncy** [comment]
This is a pretty good start! However, you seem to mix ```dcat:Catalog``` and ```dcat:Dataset```. For me, each graph we have created correspond to a ```dcat:Dataset``` and we could have 1 ```dcat:Catalog```, namely DOREMUS. I would not use the property ```dcat:record```.

I would provide a better label for the dataset, e.g.
```turtle
<http://data.doremus.org/bnf> a dcat:Dataset ;
   rdfs:label "List of musical Works and Expressions from the BnF";
   rdfs:comment "Result of the conversion of MARC records in RDF following the DOREMUS ontology coming from the Bibliothèque Nationale de France (BnF)";
```
and
```turtle
http://data.doremus.org/bnf/distribution/ttl> a dcat:Distribution ;
    rdfs:label "Turtle distribution of of the BnF dataset" ;
```

**Comment by pasqLisena** [comment]
So no connection between the `dcat:Dataset` and each record?

**Comment by rtroncy** [comment]
Nope. The connection is anyway between a ```dcat;Catalog``` and a ```CatalogRecord``` when you want to slide your catalogs into macro-units for which you want to give themes, not really what we aim to do.
