### ISSUE TITLE
Folder with multiple input files

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#7]
When choosing as input a folder in which there are multiple .xml, properties becomes cumulative.

Example:
 - file1 --> mus:U11_has_key Sol majeur
 - file2 --> mus:U11_has_key [Re majeur, Sol majeur]
 - file3 --> mus:U11_has_key [Re majeur, Re majeur, Sol majeur]
etc.

It happens with almost all properties.
Tested with BNF data.

**Comment by manowb** [comment]
Hi @pasqLisena,

Yes, I noticed this before. I fix it and I'll let you know :)

**Comment by pasqLisena** [comment]
@manowb It seems you fixed it, am I wrong? The result seems good now 😄

(except when there are multiple records as in #6 but this is another story)

Can we close this issue?

**Comment by manowb** [comment]
Yes, @pasqLisena I fixed this issue and consequently the management of different UUIDs. I close it now :)
