### ISSUE TITLE
dc vs dct

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#78]
For identifiers, 2 props are used:
- `dct:identifier` in http://data.doremus.org/expression/9dade3d9-a4b3-3d18-bfd5-6bdc8686237a
- `dc:identifier` in http://data.doremus.org/performance/398bccef-ef71-3e30-b326-150ab46d19e2

Choose one.

**Comment by rtroncy** [comment]
```dc:ientifier``` where ```dc``` is ```<http://purl.org/dc/elements/1.1/>``` should be used
