### ISSUE TITLE
Same URI in all RDF files

### ISSUE THREAD

**Issue by manowb** [DOREMUS-ANR/marc2rdf#8]
I noticed that when converting several MARCXML files, the prototype generates the same URI for each class (F22, etc.) in all RDF files. This is caused because all classes in the project are static. I will fix it too :)

**Comment by rtroncy** [comment]
Thanks @manowb for fixing this issue. Think to include the commit id when closing an issue for better tracking the evolution of the source code. You can simply reference the issue number when writing your commit message and Github will magically make the link
