### ISSUE TITLE
[PP] Euterpe - Name of the artists

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/marc2rdf#83]
In the data coming from Euterpe, sometimes the name and the function of an artist is indicated and, sometimes, only its function is known. Even if every information is in the original datasets. 

Example of a M27 Foreseen Individual Performance with a function but without a name : 
http://data.doremus.org/performance/85123fb0-e6d4-3673-a3fb-80943399d4f4/5

In the same concert, example of a M27 Foreseen Individual Performance with a function and a name : 
http://data.doremus.org/performance/85123fb0-e6d4-3673-a3fb-80943399d4f4/2

In the original data, everything is mentionned : 
```
<intervenant id="10029" libelle="Jane Birkin" role="chant" />
                <intervenant id="11242" libelle="Nobuyuki Nakajima" role="direction musicale, piano" />
                <intervenant id="10292" libelle="Takuma Sakamoto" role="trompette" />
                <intervenant id="10293" libelle="Hoshiko Yamane" role="violon" />
                <intervenant id="10294" libelle="Ichiro Onoe" role="batterie" />
```

**Comment by pasqLisena** [comment]
moved to https://github.com/DOREMUS-ANR/euterpe-converter/issues/8
