### ISSUE TITLE
[PP] Euterpe - problem with identifier

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/marc2rdf#84]
I didn't know that, in Euterpe, a given identifier could be use for different types of entities : artists, works and events.... Because of that, there is some mistakes in the data. 

For example, Serge Gainsbourg is linked with a harpsichord performance : 
F28 Expr. Creation : http://data.doremus.org/event/e2dfd382-c5fc-35a2-b6ee-844ef406ce7a
linked to this one : 
http://data.doremus.org/expression/c6cf534d-a58a-30cc-8b88-b567de50f652

Because "13521" is the identifier of : 
- a work (Tombées de nues)
- a foreseen concert (Blandine Ranou)

Before using an identifier, we have to look at its context.

**Comment by ccecconi** [comment]
Here is the xml code of a record : 
 <evenement>
            <etablissement>Cité de la musique</etablissement>
            <lieu>Salle des concerts</lieu>
            <id>12990</id>
            <titre_ligne1>Baptiste Trotignon &amp; Bojan Z / Marc Copland &amp; Bill Carrothers</titre_ligne1>
            <titre_ligne2 />
            <representations />
            <activites>
                <activite activite_id="1">concert</activite>
            </activites>
            <genres>
                <genre genre_id="7">Jazz</genre>
            </genres>
            <lien_web>http://www.citedelamusique.fr/francais/activite/concert/12990</lien_web>
            <distribution>
                <formation id="2210">Marc Copland &amp; Bill Carrothers</formation>
                <intervenant id="11058" libelle="Marc Copland" role="piano" />
                <formation id="2189">Baptiste Trotignon &amp; Bojan Z </formation>
                <intervenant id="4396" libelle="Baptiste Trotignon" role="piano" />
                <intervenant id="6684" libelle="Bojan Z" role="piano" />
            </distribution>
            <programme>
                <oeuvre>
                    <id>11939</id>
                    <titre>I've got you under my skin</titre>
                    <compositeurs>
                        <compositeur id="11444">Cole Porter</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>11940</id>
                    <titre>Talkin blues</titre>
                    <compositeurs>
                        <compositeur id="11058">Marc Copland</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>11941</id>
                    <titre>Rainy Night House</titre>
                    <compositeurs>
                        <compositeur id="11445">Joni Mitchell</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>11942</id>
                    <titre>Dolphin Dance</titre>
                    <compositeurs>
                        <compositeur id="6225">Herbie Hancock</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>11943</id>
                    <titre>Night Whispers</titre>
                    <compositeurs>
                        <compositeur id="11058">Marc Copland</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>11944</id>
                    <titre>Time was</titre>
                    <compositeurs>
                        <compositeur id="11058">Marc Copland</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>5753</id>
                    <titre>Blue in Green</titre>
                    <compositeurs>
                        <compositeur id="6304">Miles Davis</compositeur>
                    </compositeurs>
                </oeuvre>
                <oeuvre>
                    <id>8468</id>
                    <titre>All Blues</titre>
                    <compositeurs>
                        <compositeur id="6304">Miles Davis</compositeur>
                    </compositeurs>
                </oeuvre>
            </programme>
            <description>Bill Carrothers se voit contraint d'annuler sa participation au concert de ce soir avec Marc Copland. 
 En raison de mauvaises conditions climatiques, il a été dans l'impossibilité de prendre un avion pour rejoindre Paris. 
 Le déroulé de la soirée reste inchangé.

 Nous vous souhaitons un agréable concert.

 ***

 Baptiste Trotignon &amp; Bojan Z
 Le simple énoncé de ces deux noms est déjà porteur d’un vaste imaginaire. Face à face, dos à dos, main dans la main ou les trois à la fois, on sait d’emblée que le pasodoble atypique dans lequel le pianiste serbe et son complice français vont se lancer se fera, sans filet, sur le câble bien tendu d’une improvisation totale, insaisissable. Leur bagage respectif, solide et virtuose, n’est qu’un prétexte à raconter, toujours et encore, à narrer, plus que jamais, le palpable comme l’indicible. Et si chacun, bien distinctement, a prouvé en solitaire comment il domptait son propre clavier, leur rencontre d’un soir n’aura pas l’allure d’une partie de ping-pong poudre aux yeux mais plutôt d’une conversation entre vrais créateurs, entre architectes imprévisibles et passionnants.
 _

 Marc Copland &amp; Bill Carrothers 
 Deux Américains aimés par Paris et qui le lui rendent bien. Deux pianistes au style unique magnifiant leur étonnant jeu du chat et de la souris depuis déjà plusieurs années, au disque (étonnant No Choice paru en 2006) comme sur scène. À la poésie de Marc Copland répondent les entrechats de Bill Carrothers. La palette de couleurs est réellement vaste et les orientations choisies souvent osées. Car ces deux-là aiment s’égarer dans la marge, puis revenir avec mélancolie sur des sentiers plus  chaleureux pour enfin fuguer à nouveau… Qu’ils reprennent Wayne Shorter ou Neil Young, leur piano surprend, surtout dans l’abstraction. La marque des créateurs, des vrais, sans doute.</description>
        </evenement>

**Comment by pasqLisena** [comment]
moved to https://github.com/DOREMUS-ANR/euterpe-converter/issues/7
