### ISSUE TITLE
[PP] Audio Concerts - "M19 categorization" en triple

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/marc2rdf#86]
Dans la conversion des concerts audio, les descripteurs (610) ont été convertis en double, voir en triple : 
mus:U19_is_categorized_as

Exemple : 
F31 Performance : http://data.doremus.org/performance/1a7a7cc9-4e56-3a42-9b39-27b6573d1333
M43 Performed Expression : http://data.doremus.org/expression/f1290d5d-5f54-3d67-a03b-9931e36dc823

**Comment by pasqLisena** [comment]
closed in 2f1da5cb23fba2204321664258f123edb65131eb
