### ISSUE TITLE
[PP] Audio & Video Concerts - Structure des F25 Performance Plan

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/marc2rdf#88]
Il y a eu une erreur dans le mapping sur la manière d'implémenter les F25 Performance Plan dans les concerts audio et vidéo. 

Il est normal que le F25 Performance Plan de la F31 Performance soit relié à toutes les oeuvres jouées durant le concert. 

Mais les parties de concert  (M42 Performed Expression Creation) devraient être reliées à un F25 Performance Plan qui liste uniquement l'oeuvre jouée dans la partie en question. 

Or, pour l'instant, les parties de concerts sont reliées au même F25 Performance Plan que l'ensemble du concert. 

Je propose deux solutions : 
- la plus rapide : supprimer les liens entre les F25 Performance Plan et les M42 Performed Expression Creation. (On conserve le lien entre le F25 et la F31. La partie de concert reste liée directement à l'oeuvre par l'intermédiaire de M43 Performed Expression _U54 is performed Expression of_ F22).
- la plus complexe : créer un F25 pour chaque M42 qui doit être reliée à une F22. Puis, relier ce F25 spécifique au F25 de l'ensemble du concert par l'intermédiaire de la propriété P9i forms part of)

**Comment by ccecconi** [comment]
Merci Pierre pour ta correction. J'avais effectivement lu un peu vite mon schéma.... Nous avions décidé de prendre R5i is component of

**Comment by pierrechoffe** [comment]
La 1ère solution fonctionne et, bien que simplificatrice, devrait être la solution par défaut. La 2e est intéressante si l'on a le moyen de faire un mapping différencié.

**Comment by pasqLisena** [comment]
Ok, I go for solution n.1
