### ISSUE TITLE
Introduce a package manager to manage dependencies

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#9]
As it is natural, this project relies on some [third-parts dependencies](https://github.com/DOREMUS-ANR/marc2rdf#dependencies). This dependencies are currently committed in the [jars folder](../tree/master/jars). So that, for adding a new dependency, we need to download the jar, add it to the _jars_ folder and manually add it as dependency (with Eclipse wizard or writing it in the classpath).

A better way to manage this process is to use a _package manager_ that automatically download and install declared dependencies. Briefly, the _jars_ folder will disappear, replaced by a configuration file.

For Java, the best alternatives are _Maven_ and _Gradle_. I prefer the latter because its configuration file is [pretty cleaner](https://thomassundberg.wordpress.com/2014/07/02/comparing-maven-and-gradle/). There is native support in IntelliJ and fully support with a plugin for [Eclipse](http://www.vogella.com/tutorials/EclipseGradle/article.html) and it supports all libraries that are on https://maven-repository.com/ (and not only).

Unique disadvantage (common to Maven and Gradle): we need to change a bit the structure of the project but, if you agree with it, I can do it quite fast.

**Comment by manowb** [comment]
Hi @pasqLisena,

I totally agree with you especially if there is a way to clean up the code and to facilitate the installation of the tool. 

I don't know Gradle so yes thank you to do it :)

**Comment by rtroncy** [comment]
+1 as well. Assigning @pasqLisena to implement it.

**Comment by pasqLisena** [comment]
Done, only 2 libraries remained in the `libs` folder (virtuoso drivers).

I suggest you to re-import the project in Eclipse (as in the [tutorial](http://www.vogella.com/tutorials/EclipseGradle/article.html), paragraphs 1 and 4). Then choose the task `run` from the Gradle tab (on the bottom).

I am available for any issue.
