### ISSUE TITLE
[PP] Lieu Philharmonie de Paris

### ISSUE THREAD

**Issue by ccecconi** [DOREMUS-ANR/marc2rdf#90]
Attention, tu as mis un lien "same as" entre Philharmonie de Paris et Cité de la musique. Ce n'est pas tout à fait juste. 

Cela fait qu'un concert tel que celui-ci est indiqué comme ayant eu lieu à la Philharmonie, alors qu'en 2003, elle n'existait pas encore : http://data.doremus.org/performance/42c4a85b-20cc-3f65-a34e-70a78424f59f

La **collectivité Philharmonie** (ou, de son vrai nom "Cité de la musique - Philharmonie de Paris) englobe, depuis janvier 2015 : 
- le **bâtiment Philharmonie de Paris** (et les salles qui s'y trouvent)
- le **bâtiment Cité de la musique** (et les salles qui s'y trouvent)

La **collectivité Cité de la musique** englobe, avant janvier 2015 : 
- le **bâtiment Cité de la musique** (et les salles qui s'y trouvent)
- le **bâtiment Salle Pleyel**

La collectivité "**Cité de la musique"** devient (mais n'est pas la même chose) la collectivité **Cité de la musique-Philharmonie de Paris** en 2015.

**Comment by ccecconi** [comment]
Il faudrait conserver le bâtiment tel qu'il est indiqué dans les concerts (cf. mapping des vidéo et des audio, l. 60 à l.62). 
Comme on le voit dans l'évenement d'enregistrement, le concert cité ci-dessus a eu lieu dans le bâtiment de la Cité de la musique, dans la salle des concerts (qui se trouve dans la Cité de la musique)
http://data.doremus.org/event/2d9e0831-edff-307f-9681-83a55ccd8876

**Comment by pasqLisena** [comment]
Data validity during the time is out the scope of the project :)

In the whole dataset we represent "physical places" (a building, a city, a country) going beyond the "label" which those places have/had in a specific point in time.

Example: now _Leiningrad_ has another name
http://data.doremus.org/performance/9147072c-97d6-3753-91be-c7f0a5bcc2b2
